### PR TITLE
Fix/243 bg task processing

### LINKED ISSUE #243: Replace iOS's deprecated performFetchWithCompletionHandler with BGTaskScheduler
The current version of the library uses the [deprecated `performFetchWithCompletionHandler`](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623125-application) so I propose the replacement of it with the [recomended `BGTaskScheduler` ](https://developer.apple.com/documentation/backgroundtasks/bgapprefreshtask).

### PR DESCRIPTION
**Pull request by ened**
Fixes #243 - looking for feedback

### CODE REVIEW

**Comment by Alexays** [comment]
Hi @ened, thx for your PR, lgtm.
You should also update comment to mention iOS for `callbackDispatcher `
https://github.com/fluttercommunity/flutter_workmanager/blob/708ced673d06c46b25eb4a4863d028aa93de9cad/lib/src/workmanager.dart#L125

**Comment by ened** [comment]
Thank you for checking the PR, @Alexays.

**Comment by Nicholas-Ho** [comment]
Hi @ened, I think the pub.dev README hasn't been updated! It doesn't have the "Customisation - iOS (BGTaskScheduler only)" bit

**Comment by ened** [comment]
@Nicholas-Ho you are right, this was only added to the GH repo. Will ensure it's updated with the next pre-release version. Thank you!

**Pull request merged**
