### PR TITLE
iOS task cancellation

### PR DESCRIPTION
**Pull request by tuyen-vuduc**
- allows to cancel iOS BGTask by specified ID or all

### CODE REVIEW

**Comment by ened** [comment]
Very cool. Thank you @tuyen-vuduc for these additions.

Could you kindly update the integration test and to use them? https://github.com/fluttercommunity/flutter_workmanager/blob/main/example/integration_test/workmanager_integration_test.dart

Also, please update the CHANGELOG.md file with these changes.

**Comment by tuyen-vuduc** [comment]
@ened How could I run this integration test? Do you have a guide? Your code is not what mentioned in Flutter docs.

**Comment by tuyen-vuduc** [comment]
@ened Could you help check the test failure on Android?

**Comment by ened** [comment]
I will check today. From a glimpse it seems the "cancel*" calls in the integration test are not "await"'ed.

**Comment by ened** [comment]
hi @tuyen-vuduc could you kindly rebase - I tried to push to your repository but do not have permission. Please move your change in the CHANGELOG.md to the next version, `0.5.0-dev.8`. Sorry for the inconvenience.

**Comment by tuyen-vuduc** [comment]
@ened I rebased. Please help check out.

**Comment by ened** [comment]
Thank you for your contribution and your patience @tuyen-vuduc

**Pull request merged**
