### PR TITLE
feat: add factory pattern to Workmanager so it can be easely mock

### PR DESCRIPTION
**Pull request by Pierre-Monier**
This PR solve a problem my team face while writing unit tests. We can't mock Workmanager because it only use static method. I add a factory constructor so the end user just have to do `Workmanager().initialize(fct)` instead of `Workmanager.initialize(fct)`. Now we can easily mock the Workmanager class in unit test. I write an example test file, here a sample : 

```dart
void mySetUpWrapper() {
  GetIt.I<Workmanager>().initialize(testCallBackDispatcher);
  GetIt.I<Workmanager>().cancelAll();
}

void main() {
  setUpAll(() {
    GetIt.I.registerSingleton<Workmanager>(MockWorkmanager());
  });

  test('mySetUpWrapper calls the Workmanager initialize and cancelAll method', () {
    mySetUpWrapper();

    verify(GetIt.I<Workmanager>().initialize(testCallBackDispatcher));
    verify(GetIt.I<Workmanager>().cancelAll());
  });
}
```

### CODE REVIEW

**Comment by ened** [comment]
Thank you @Pierre-Monier for this PR. We will get a few other PRs in first, then address this one. Are you available to rebase this PR if necessary? Thank you.

**Comment by Pierre-Monier** [comment]
Yes of course :)

**Comment by ened** [comment]
Hi @Pierre-Monier thank you again for the PR and it looks quite good, will only have a few nitpicks perhaps.

Could you convert test/workmanager_mock_test_example.dart into an actual unit test, perhaps even utilising the new factory pattern. You could do a single method and we will complete the rest of the methods at a later stage. Do you have time to do this?

**Comment by Pierre-Monier** [comment]
What did you mean by "an actual unit test" ?

**Comment by ened** [comment]
A test in the "test" folder which instantiates the plug-in and runs a few methods. Run it using the IDE or `flutter test`.

https://flutter.dev/docs/cookbook/testing/unit/introduction

**Comment by Pierre-Monier** [comment]
Ok my bad I thought that I had written a real unit test in the first place. I can do that this weekend

**Comment by Pierre-Monier** [comment]
I wrote some very basic test, It will be great to test the actual Workmanager logic, but I think in order to achieve that we need a helper test method who check if a background task is executed.

**Comment by ened** [comment]
Hi @Pierre-Monier thank you for adding the test. We will merge with this first. Some improvements could be done in future PRs:
 - Remove get_it dependency (it's only there for the test)
 - Mock all method calls. The idea of a unit test is to verify the invocation from library users calls the correct platform method with the correct parameters. You are right that we need different testing methods to check if background tasks are executed. We may not be able to check that in detail due to the very asynchronous nature of this package, but a [integration test](https://flutter.dev/docs/cookbook/testing/integration/introduction) could help us to make sure the platform calls are handled. Additional platform specific tests could be written to ensure the platform sets up the right things with WorkManager etc.

Thank you again!

**Pull request merged**
