### PR TITLE
Improvement on iOS

### PR DESCRIPTION
**Pull request by xunreal75**
Hi

I added BGAppRefresh on iOS as periodic task - this will have normally more calls than a refresh-task.
- time for a AppRefresh is limited to 29sec
Also I updated readme and and example
Added backgroundrefresh-permission-check and open iOS device-settings if not permitted  on iOS (init work manager)

### CODE REVIEW

**Review by asifakhtar98 — APPROVED** [review]

**Comment by asifakhtar98** [comment]
I imported the package in pubsec.yaml like this-
  workmanager:
    git:
      url: https://github.com/xunreal75/flutter_workmanager.git
      branch: iOS_notWorkingUpdate

The two code blocks are showing an error-

  if (Platform.isIOS) {
//here you can check whether background refresh is activated in iOS settings
    var hasPermissions = await Workmanager().checkBackgroundRefreshPermission();
    if (hasPermissions != BackgroundAuthorisationState.available) {}
  }


Errors in console before running:
1. Error: Undefined name 'BackgroundAuthorisationState'.
    if (hasPermissions != BackgroundAuthorisationState.available) {}

2. The method 'checkBackgroundRefreshPermission' isn't defined for the class 'Workmanager'.
 - 'Workmanager' is from 'package:workmanager/src/workmanager.dart' ('../../flutter/.pub-cache/git/flutter_workmanager-29bb7f11bc38fff2735888615b8fc79d05a3c51e/lib/src/workmanager.dart').
 
3. Try correcting the name to the name of an existing method, or defining a method named 'checkBackgroundRefreshPermission'.
    var hasPermissions = await Workmanager().checkBackgroundRefreshPermission();

**Comment by xunreal75** [comment]
Hi

at the moment I've no glue. On my devices is ist Running without errors.
in your updated repo you should have two extra files where the missing name and method is.

First is: ios/Classes/CheckAuthorisation.swift there is the missing checkBackgroundRefreshPermission
 this is implemented in work manger dart line 169 and below
```
  Future<BackgroundAuthorisationState>
      checkBackgroundRefreshPermission() async {
    try {
      var result = await _foregroundChannel.invokeMethod<Object>(
        'checkBackgroundRefreshPermission',
        JsonMapperHelper.toInitializeMethodArgument(
            isInDebugMode: _isInDebugMode,
            callbackHandle:
                0), //must provide an argument for switch statement on Swift
      );
```

2. BackgroundAuthorisationState is referenced in options.dart -> lib/src/options.dart
It's coded from line 69 and below
```
/// await Workmanager().checkBackgroundRefreshPermission(); to check these permissions
/// requestBackgroundAuthorisation only once and respect users choice
enum BackgroundAuthorisationState {
  /// iOS Setting Backgroundwork is enabled.
  available,

  /// iOS Setting Backgroundwork is disabled in settings. You shoud request for permissions call
  denied,

  /// iOS Setting is under parental control etc. Can't be changed by user
  restricted,

  ///unknown state
  unknown
}
```

Perhaps something goes wrong on import. Do you have these 2 parts in your code?
In the commits are the files correct.

Lars

**Comment by ened** [comment]
Hi everyone, thank you for improving the plugin. At the moment, I am unable to review this PR properly due to its complexity. Please can you split it into multiple smaller PRs that address smaller problems, first? I will then be able to spent appropriate time to review. If this PR fixes a bug, please create an Issue first, so we can properly analyse and debug beforehand. Thank you.

**Comment by PascalGehring** [comment]
It would be great if this could be merged!

**Review by PascalGehring — APPROVED** [review]

**Comment by delfme** [comment]
@xunreal75 hello. I don't get any error by using your branch but task simply doesn't run.
Can you please check that example works properly even on latest flutter master?

**Comment by xunreal75** [comment]
Hi

I'll inspect it this week.

**Comment by kingvhit** [comment]
@xunreal75 : Hi, any updated on it ?

**Comment by iosephmagno** [comment]
@xunreal75 that looks great 👏
But why dont we integrate BGProcessingTask for longer tasks (> 29 sec) ?

Flutter_downloader and fultter_uploader integrated NSURLSessionDownloadTask which also allow long time process.
https://pub.dev/packages/flutter_downloader

**Comment by xunreal75** [comment]
Hi

I think your approach aims to start a in foreground running app. Workmanager aims to background execution (headless).
I could link Flutter_downloader and uploader or search other solutions which is blowing up the project.
And,I would recommend to review by the owners first.

The third possibility to wake-up an iOS app by notification is not (easy) applicable with this plugin.

**Comment by xunreal75** [comment]
PS:

BGPROCESSINGTASK can run longer than 29 sec. See example.

You don't know when the task will started.

**Comment by xunreal75** [comment]
Because of differences to Android ( where simpleOnOffTask starts immediately) I decided the simpleOnOffTask and his subExamples starts immediately      in background but is limited to 30 sec by iOS.

**Comment by delfme** [comment]
Now it is clear! Greab job 🚀
I have just a doubt  with registerPeriodicTask on iOS. Can you please check below my recap?

- registerOneOffTask
Now starts immediately on iOS but lasts 29sec.

- registeriOSBackgroundProcessingTask
Long running oneoff background task on iOS. It last more than 29sec but doesnt start immediately

- registerPeriodicTask
This is for a scheduled task. It is not clear how long it will last on iOS, is it a long lasting task or <29sec task?

**Comment by kingvhit** [comment]
It seem the `initialDelay` is ignored on iOS side, I saw it on comment. Is it correct? I would like to set the period background tasks every midnight, the task seem not long background, so I intend to use `registerPeriodicTask` for both iOS and Android.


I am checking the capiblity on this PR for iOS side, Android works.

**Comment by xunreal75** [comment]
Sorry at midnight is impossible, Backgroundprocessing is randomly called by iOS - see remarks .

Midnight update with iOS is only possible with pushNotifications wich wake up your app from background- initiated by an external server and not with workmanager. 

When you are interested look at

[(https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app)] Apple developer doc.

**Comment by kingvhit** [comment]
@xunreal75  Thanks for your reply, seem Apple has retricted the scheduling and we should use a trick (by remote notification... )

Btw, skip the exactly time for trigger event, back to Work Manager, can I set period tasks one a day (any time) ? It might we should use 
`registerPeriodicTask` on this cases, I tried 

```
      if (Platform.isAndroid) {
        // Periodic task registration
        Workmanager().registerPeriodicTask(
            kWorkUniqueName, kWorkAndroidTaskIdentifier,
            initialDelay: Duration(seconds: differentSeconds),
            // When no frequency is provided the default 15 minutes is set.
            // Minimum frequency is 15 min. Android will automatically change your frequency to 15 min if you have configured a lower frequency.
            frequency: const Duration(days: 1),
            existingWorkPolicy: ExistingWorkPolicy.replace);
      } else if (Platform.isIOS) {
        Workmanager()
            .registerPeriodicTask(kWorkUniqueName, kWorkIOSTaskIdentifier,
                initialDelay: Duration(seconds: differentSeconds),
                // When no frequency is provided the default 2 minutes is set.
                frequency: const Duration(days: 1),
                existingWorkPolicy: ExistingWorkPolicy.replace);
      }
```

For Android It works, but I don't think that work with iOS with `initialDelay` property. So, that mean for iOS it only works with `frequency` and `initialDelay` is skipped, right?

**Comment by iosephmagno** [comment]
> Now it is clear! Greab job 🚀
> 
> I have just a doubt with registerPeriodicTask on iOS. Can you please check below my recap?
> 
> * registerOneOffTask
> 
> Now starts immediately on both android and iOS. On iOS it lasts only 29sec.
> 
> * registeriOSBackgroundProcessingTask
> 
> Long running oneoff background task to be used specifically on iOS. It last more than 29sec but doesnt start immediately
> 
> * registerPeriodicTask
> 
> This is for a scheduled task on both android and iOS. It is not clear how long it will last on iOS, is it a long lasting task or a 29sec task?

@xunreal75 I guess your reply got lost somehow

**Comment by iosephmagno** [comment]
> Now it is clear! Greab job 🚀 I have just a doubt with registerPeriodicTask on iOS. Can you please check below my recap?
> 
> * registerOneOffTask
>   Now starts immediately on both android and iOS. On iOS it lasts only 29sec.
> * registeriOSBackgroundProcessingTask
>   Long running oneoff background task to be used specifically on iOS. It last more than 29sec but doesnt start immediately
> * registerPeriodicTask
>   This is for a scheduled task on both android and iOS. It is not clear how long it will last on iOS, is it a long lasting task or a 29sec task?

@xunreal75 could you be so kind as to clarify my last point here?

**Comment by xunreal75** [comment]
@iosephmagno

registerOneOffTask
- Now starts immediately on both android and iOS. On iOS it lasts only 29sec.

registeriOSBackgroundProcessingTask
- Long running oneoff background task to be used specifically on iOS. It last more than 29sec but doesnt start immediately.

registerPeriodicTask
- This is for a scheduled task on both android and iOS. It is not clear how long it will last on iOS, it's a 29sec task, but doesnt start immediately.

**Comment by iosephmagno** [comment]
Thanks @xunreal75 🙏
Lets say I run one registerOneOffTask in fireground and keep app opened in foreground. Will the task be killed after 29sec or it will keep running as long as app is in foreground?

**Comment by iosephmagno** [comment]
> @xunreal75 Thanks for your reply, seem Apple has retricted the scheduling and we should use a trick (by remote notification... )
> 
> Btw, skip the exactly time for trigger event, back to Work Manager, can I set period tasks one a day (any time) ? It might we should use `registerPeriodicTask` on this cases, I tried
> 
> ```
>       if (Platform.isAndroid) {
>         // Periodic task registration
>         Workmanager().registerPeriodicTask(
>             kWorkUniqueName, kWorkAndroidTaskIdentifier,
>             initialDelay: Duration(seconds: differentSeconds),
>             // When no frequency is provided the default 15 minutes is set.
>             // Minimum frequency is 15 min. Android will automatically change your frequency to 15 min if you have configured a lower frequency.
>             frequency: const Duration(days: 1),
>             existingWorkPolicy: ExistingWorkPolicy.replace);
>       } else if (Platform.isIOS) {
>         Workmanager()
>             .registerPeriodicTask(kWorkUniqueName, kWorkIOSTaskIdentifier,
>                 initialDelay: Duration(seconds: differentSeconds),
>                 // When no frequency is provided the default 2 minutes is set.
>                 frequency: const Duration(days: 1),
>                 existingWorkPolicy: ExistingWorkPolicy.replace);
>       }
> ```
> 
> For Android It works, but I don't think that work with iOS with `initialDelay` property. So, that mean for iOS it only works with `frequency` and `initialDelay` is skipped, right?


Remote notifications approach doesnt work on IOS :) You should use silent notifications and system tend to kill most of them or serve them when it wants to. So waking up app via notifications with the scope of triggering a backup is not an IOS thing.

**Comment by xunreal75** [comment]
OneOffTask  is running in Background for max 29 secs  - If it's longer running,the task will killed.

**Comment by iosephmagno** [comment]
Thx 👍 will test this out

**Review by PascalGehring — APPROVED** [review]

**Comment by josh-burton** [comment]
Can a periodic task schedule an iOSBackgroundProcessingTask?

e.g. can I have a periodic task that runs every 15 minutes to check if the app needs to upload files, and if it does, have the periodic task register a background processing task to upload the files?

**Comment by xunreal75** [comment]
- [ ] Sorry.  It's impossible when app is in background due Apple limitations to update every 15 sec. Only choice is to send silent notification. You can take a look at  [apple](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app).

Anyway when you register a background processing task from apprefresh, you will never know when it will updated.

**Comment by xunreal75** [comment]
At the moment I have no time to split iOS Parts to join with main. Perhaps anybody can implement iOS parts.

**Comment by josh-burton** [comment]
Well this is a sad outcome. I've been using this branch with great success.

Maintainers - how can we get this merged?

**Comment by delfme** [comment]
Sorry I might have missed somthing but I merged your branch time ago to my fotk with no or minimal conflicts. Any issue?

**Comment by josh-burton** [comment]
> Sorry I might have missed somthing but I merged your branch time ago to my fotk with no or minimal conflicts. Any issue?

Is your fork published on pub?

Would be really great to re-open this PR and get it merged.

**Comment by delfme** [comment]
? It is already here, you dont need my repo https://github.com/xunreal75/flutter_workmanager/tree/iOS_notWorkingUpdate

**Comment by ened** [comment]
@josh-burton we can work on it. Are you able to reopen a new PR?

**Comment by DaemonChoejur** [comment]
any one working on the iOS update for it?

**Comment by iosephmagno** [comment]
> @josh-burton we can work on it. Are you able to reopen a new PR?

@ened just saw this. I cannotreopem PR but will invite you to our fork. We merged that PR for ios and had no issue with it

**Comment by ened** [comment]
@iosephmagno want to open a new PR and own the changes?

**Comment by iosephmagno** [comment]
Nope, thought that PR's author removed the code and you might want to have a look at it. If that is the case, we merged that code and is available inside our fork (gave you full access to it).

**Comment by udoy-touhid** [comment]
Really sad this has been closed. This feature is THE missing piece of the puzzle. Could this be merged please?
cc: @xunreal75 @ened

**Pull request closed without merging**
