### PR TITLE
feat!: iOS major enhancements BGAppRefreshTask, BGProcessingTask, beginBackgroundTask, printScheduledTasks

### LINKED ISSUE #295: Improved iOS BGTaskScheduler request options and scheduling
@ened I have been reviewing the work completed in #243 and working with the latest version of this package that includes those changes. I have some comments and questions that warranted a new issue and discussion, summarized here.

### `BGProcessingTask` vs `BGAppRefreshTask`

Is there a reason that this was implemented entirely as a `BGProcessingTaskRequest`? Is there any plan to allow for this request to be a `BGAppRefreshTaskRequest` to handle smaller, more bite size operations? `BGProcessingTaskRequest` is intended for tasks that take "minutes" and is overkill for more trivial background tasks. It may be detrimental to iOS scheduling to use this request type when it is not necessary.

I am not sure if iOS has greater restrictions on the number of times `BGProcessingTask` can be executed vs `BGAppRefreshTask`. I assume that `BGAppRefreshTask` can be executed and scheduled **more often** per iOS guidelines. I am trying to use this in order to perform home screen widget background refresh tasks and these are fairly lightweight operations so it makes more sense to use a `BGAppRefreshTaskRequest` and not get penalized by the iOS scheduler.

### Continuous Scheduling 

Second, it does not seem like there is a way to schedule these operations in a **continuous** manner. This is actually the purpose of `BGAppRefreshTask` and this is clearly displayed by Apple in the following link and code example, by Apple:

https://developer.apple.com/documentation/backgroundtasks/refreshing_and_maintaining_your_app_using_background_tasks

If you download that code example you will see the following:

```swift
BGTaskScheduler.shared.register(forTaskWithIdentifier: "com.example.apple", using: nil) { task in
    self.handleAppRefresh(task: task as! BGAppRefreshTask)
}
```

Then later on:

```swift
func scheduleAppRefresh() {
    let request = BGAppRefreshTaskRequest(identifier: "com.example.apple")
    request.earliestBeginDate = Date(timeIntervalSinceNow: 15 * 60) // Fetch no earlier than 15 minutes from now
    
    do {
        try BGTaskScheduler.shared.submit(request)
    } catch {
        print("Could not schedule app refresh: \(error)")
    }
}

func handleAppRefresh(task: BGAppRefreshTask) {
    scheduleAppRefresh()
    
    ....

    lastOperation.completionBlock = {
        task.setTaskCompleted(success: !lastOperation.isCancelled)
    }

    queue.addOperations(operations, waitUntilFinished: false)
}
```

Do you notice how `handleAppRefresh()` calls `scheduleAppRefresh()` so that this task can be continuously scheduled?This is perfect for things like home screen widgets and the purpose of `BGProcessingTask`. Right now, there are two limitations with `flutter_workmanager`:

1.  Background tasks cannot be assigned as `BGAppRefreshTask`
2. There is no way to control the continuous scheduling because this is not accessible by `SwiftWorkmanagerPlugin`

Even if I wanted to use `BGProcessingTask` (as it is currently implemented), `SwiftWorkmanagerPlugin` does not expose a hook in the `SwiftWorkmanagerPlugin.handle()` method to kick off another scheduled task after the current task completes.

### Discussion

Please let me know if that makes sense or if you have any questions! I think this would be great capability to add and is inline with how iOS intends `BGTaskScheduler` to be used. Look forward to discussing further!

### LINKED ISSUE #450: 🐞iOS: registerOneOffTask never registers with callbackDispatcher
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |      0.5.0         |
| Xcode version        |      14.1         |
| Swift version        |       5.7.1        |
| iOS deployment target|      11.0         |

**Describe the error**

Have followed all the directions in the iOS setup and guides but am unable to get the plugin to work correctly. No errors are thrown - the callback dispatcher is just never called. The code works without fault on Android. The test environment is a physical device (iPhone XS running iOS 16.1.2) and is being debugged from XCode. The Info.plist has been configured with the correct task indentifier and backgroundFetch seems to work as expected and triggers the callbackDispatcher, but registering a one off task doesn't. 

callbackDispatcher as top level function:
```@pragma('vm:entry-point')
void callbackDispatcher() {
  Workmanager().executeTask((taskName, inputData) {
    stderr.writeln(
        'Flutter VM, BACKGROUND TASK: Background task called! $taskName, extra data: $inputData');

    return Future.value(true);
  });
}
```

my AppDelegate.swift: 

```
@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {

  override func userNotificationCenter(_ center: UNUserNotificationCenter,
                                         willPresent notification: UNNotification,
                                         withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
         completionHandler(.alert) // shows banner even if app is in foreground
     }
    
  

  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
      // This is required to make any communication available in the action isolate.
        UNUserNotificationCenter.current().delegate = self
        FlutterLocalNotificationsPlugin.setPluginRegistrantCallback { (registry) in
          GeneratedPluginRegistrant.register(with: registry)
        }
        //WorkmanagerPlugin.register(with: self!.registrar(forPlugin: "com.v2software.onchocks.onchocks-background-logging"))
        WorkmanagerPlugin.registerTask(withIdentifier: "com.v2software.onchocks.onchocks-background-logging")
      
        UIApplication.shared.setMinimumBackgroundFetchInterval(TimeInterval(60*15))
        GeneratedPluginRegistrant.register(with: self)
        if #available(iOS 10.0, *) {
            UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
        }
      
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```
I'm calling registerOneOffTask from a Popupmenuitem: 

```
PopupMenuItem(
                              child: const Text('Record flight'),
                              onTap: () async {
                                print('Registering new task');
                                try {
                                  await Workmanager().registerOneOffTask(
                                      'com.v2software.onchocks.onchocks-background-logging',
                                      'com.v2software.onchocks.onchocks-background-logging',
                                      tag: 'ThisIsANewTag',
          
                                      inputData: {
                                        'user': user?.user.uid,
                                        'registeredEvent': true,
                                      },
                                      initialDelay: Duration.zero,
                                      existingWorkPolicy:
                                          ExistingWorkPolicy.replace);
                                } catch (err) {
                                  print(err.toString());
                                }
                              },
                            ),
```

When calling the onTap function this is the debug output: 
```
2022-12-12 21:03:51.281401+1030 Runner[3948:242838] flutter: Registering new task
2022-12-12 21:04:17.589698+1030 Runner[3948:254976] [tcp] tcp_input [C2.1.1:3] flags=[R] seq=4218016391, ack=0, win=0 state=LAST_ACK rcv_nxt=4218016391, snd_una=1941703970
2022-12-12 21:04:17.592510+1030 Runner[3948:254976] [tcp] tcp_input [C2.1.1:3] flags=[R] seq=4218016391, ack=0, win=0 state=CLOSED rcv_nxt=4218016391, snd_una=1941703970
2022-12-12 21:04:17.593167+1030 Runner[3948:254976] [tcp] tcp_input [C2.1.1:3] flags=[R] seq=4218016391, ack=0, win=0 state=CLOSED rcv_nxt=4218016391, snd_una=1941703970
```

I noticed that the callback will fire at a very random time (not associated with any input or background fetch) and the task will be in the queue but missing the input data. 

I was expecting behaviour similar to what I am seeing in Android where the callback function is triggered nearly immediately upon registering the task. Am I missunderstanding the functionality of this package or have I missused it? 

**[✓] Flutter (Channel stable, 3.0.3, on macOS 13.0.1 22A400 darwin-x64, locale en-AU)
    • Flutter version 3.0.3 at /Users/ChrisBrislin/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (6 months ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/ChrisBrislin/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (4 available)
    • Chris iphone (mobile) • 00008020-001870340E92002E            • ios
      • iOS 16.1.2 20B110
    • iPhone 14 (mobile)    • 91A06788-785D-40B3-AEA8-77AED473ECCF • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)       • macos                                • darwin-x64
      • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)          • chrome                               • web-javascript
      • Google Chrome 108.0.5359.98

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!**

### LINKED ISSUE #497: 🐞inputData on iOS is null
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |     0.5.1      |
| Xcode version        |     14.2          |
| Swift version        |        5.7.2       |
| iOS deployment target|       13.0        |

**Describe the error**

inputData is not working on iOS - when task executed I get null.

Code fragments:

```
await Workmanager().initialize(
  callbackDispatcher,
);

await Workmanager().registerOneOffTask(
  'fetchLocationTask',
  'fetchLocationTask',
  tag: orderId,
  initialDelay: const Duration(minutes: 1),
  constraints: Constraints(
  networkType: NetworkType.connected,
  ),
  inputData: <String, String>{'orderId': orderId},
);
```

In main.dart:

```
@pragma(
  'vm:entry-point',
)
void callbackDispatcher() {
  Workmanager().executeTask((task, inputData) async {
    DartPluginRegistrant.ensureInitialized();
    ...
}
```

When task executed on Android there is everything ok, but on iOS I get inputData = null.

**Output of `flutter doctor -v`**

[✓] Flutter (Channel stable, 3.10.6, on macOS 12.6 21G115 darwin-arm64, locale en-PL)
    • Flutter version 3.10.6 on channel stable at /opt/homebrew/Caskroom/flutter/3.10.2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (4 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/paulinabonikowska/Library/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/paulinabonikowska/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                            • android-arm64  • Android 13 (API 33) (emulator)
    • iPhone (Paulina) (mobile)   • ebda837e6194bfe3ab688b40e6e071ab353b3d62 • ios            • iOS 15.7.6 19H349
    • macOS (desktop)             • macos                                    • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

### PR DESCRIPTION
**Pull request by absar**
[Closes](fix:) #295
[Closes](feat:) #450
[Closes](feat:) #497

Due to iOS side of this plugin falling behind Android it was necessary to do a major overhaul on iOS side. In summary the new changes are:
- iOS now supports one off immediate tasks `Workmanager.registerOneOffTask` which now uses iOS `beginBackgroundTask` instead of previous `BGAppRefreshTask` solution, migration guide is created for this. The reason to not use BGAppRefreshTask is to make it in line with Android side design and tackle some items discussed in #295
- New periodic tasks `Workmanager.registerPeriodicTask` which uses iOS `BGAppRefreshTask`
- New long running tasks `Workmanager.registerProcessingTask` using iOS `BGProcessingTask`, which was previously being done by `registerOneOffTask`. If or when Android side feature request #236 is done that should be linked to `Workmanager.registerProcessingTask` to have same feature on both platforms
- New `Workmanager.checkBackgroundRefreshPermission` to check Background App Refresh permission. On iOS user can disable `Background App Refresh` permission anytime, hence background tasks can only run if user has granted the permission.
With `Workmanager.checkBackgroundRefreshPermission` you can check whether background app refresh is enabled
- `Workmanager.printScheduledTasks` to print details of scheduled tasks to console. To be used during development/debugging. This will to some extent give developers some confidence that tasks are really scheduled and iOS will trigger at some point in the future
- Example App has been updated to use the new methods. A new button is added to make it easy to check the status of tasks, it prints scheduled task details to console and displays the saved shared preferences values on screen
- iOS documentation updates to minimize confusion and iOS understanding issues. Readme, iOS setup and API level docs are updated
- A migration section is created for breaking changes

### Migration
BREAKING CHANGE: This PR has some breaking changes for iOS:
- Workmanager.registerOneOffTask was previously using iOS **BGProcessingTask**, now it will be an immediate run task which will continue in the background if user leaves the App. Since the previous solution meant the one off task will only run if the device is idle and as often experienced only when device is charging, in practice it means somewhere at night, or not at all during that day, because **BGProcessingTask** is meant for long running tasks. The new solution makes it more in line with Android except it does not support **initialDelay**
- If you need the old behavior you can use the new iOS only method `Workmanager.registerProcessingTask`:
  1. Replace `Workmanager().registerOneOffTask` with `Workmanager().registerProcessingTask` in your App
  1. Replace `WorkmanagerPlugin.registerTask` with `WorkmanagerPlugin.registerBGProcessingTask` in `AppDelegate.swift`
- Workmanager.registerOneOffTask does not support **initialDelay**
- Workmanager.registerOneOffTask now supports **inputData** which was always returning null in the previous solution
- Workmanager.registerOneOffTask now does NOT require `WorkmanagerPlugin.registerTask` call in `AppDelegate.swift` hence remove the call

I am not a native iOS developer but tried to address my own needs after not finding any solution and waiting for too long, it will help me if you guys test and raise any issues even if this PR doesn't get merged, i will try to maintain my branch https://github.com/absar/flutter_workmanager/tree/ios-bg-tasks-enh-final

Shoutout to Lars Huth/xunreal75 for his attempt in 2022, his work helped a lot during this PR

### CODE REVIEW

**Comment by ened** [comment]
@absar Impressive amount of work. 

Something initial - the permission check and APIs should be done with `permission_handler` or any other plugin. I suggest we move that out of here and add a PR in that project. 

Will start reviewing asap, are you planing to add more changes soon?

**Comment by absar** [comment]
@ened 
> Something initial - the permission check and APIs should be done with permission_handler or any other plugin. I suggest we move that out of here and add a PR in that project.

I created a feature request in `permission_handler` https://github.com/Baseflow/flutter-permission-handler/issues/1174, although I will not be able to create a PR since that is using purely Objective C not swift, would be nice if someone helps in it. For the time being we can leave the current implementation here in workmanager and when `permission_handler` releases a version with Background App Refresh permission we will deprecate it here and ask users to switch to `permission_handler`. Having this permission is necessary since workmanager on iOS will be handicapped if user disables the permission and developers will not know what happened

> Will start reviewing asap, are you planing to add more changes soon?

I am done with it for now. Have left one or two TODOs just for code cleanups which I will do once this PRs direction is finalized

**Comment by chentetran** [comment]
Just wanna say thank you @absar for finally building these features out. I'm just started planning features in my app that rely on this, and your timing could not be any better :).

**Comment by scottynoshotty** [comment]
I pulled this in via my pubspec.yaml and am now successfully dispatching one off tasks on iOS. Huge thanks to the author. One note is that to get it to succeed on iOS I had to initialize with isInDebugMode true

```
  Workmanager().initialize(callbackDispatcher, isInDebugMode: true);

```

If I did not set that flag when the task was dispatched iOS would throw some error about notifications and the app not being run in debug mode and/or on iOS 9 or lower. Small workaround and with that it all works great.

**Comment by f1dz** [comment]
Tried using real device on iPhone XR using iOS 17.0.3. I can say that this update/PR is working well with small piece of example code. Will try to implement in the real project later.

**Comment by malthee** [comment]
This looks really promising, any plan on when this will be merged? Our app could really use these features

**Comment by ened** [comment]
Will look at it asap

**Comment by Cobolt77** [comment]
Impressive feat! Exactly what was missing for our IOS needs. Will use your branch until it is in the official package. Thanks a lot!

**Comment by mvn-hangtran-dn** [comment]
Do you have any schedule to deploy this PR? Please let us know if you can. Many thanks.

**Comment by yevhenii-dubinin** [comment]
@absar  awesome update 
already have tested your example in testFlight 
and notice that periodic and processing tasks work only when app is in background or foreground state,
but when app is closed then tasks don't fired  
is it correct behaviour?

**Comment by xunreal75** [comment]
Yes it's the correct behavior see [https://developer.apple.com/documentation/backgroundtasks/bgprocessingtask](Apple Doc)

If the app is killed, the BGProcessing is killed too.

**Comment by lora-explora** [comment]
Hi, another ping asking when this PR will be merged. Very curious to try it!

**Comment by TheRedSpy15** [comment]
Getting an error when trying to build:
```
Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): Type 'WorkmanagerPlugin' has no member 'registerBGProcessingTask'
```

**Comment by ened** [comment]
@absar `permission_handler` now supports the background app refresh check (I sent a PR a while back). We are clear to remove the permission code from your PR and start thinking about the merge. :)

**Comment by Flutter36** [comment]
Hi, I was looking at refreshing tokens in the background using work manager. On IOS, is it possible to trigger one of task with same ids multiple times? If I have to permit the ids upfront, then I cant register one off task few mins before the token expiry to refresh it.  Any suggestions on how to do this?

**Comment by micheleselea** [comment]
I understand the difference between BGProcessingTask and BGAppRefreshTask, so the new registerPeriodicTask  now use BGAppRefreshTask to let task start immediately. The periodic call is 15 minutes default, but the task should not take longer than 30 seconds for iOS constraints. So what is not clear to me, is this: what if I need to get information from the network (suppose incoming messages) if after 30 seconds my task is killed I have to wait 14 minutes and 30 seconds for next check?

**Comment by micheleselea** [comment]
Which is the difference (from iOS POV) of using registerPeriodicTask or registerOneOffTask that do a registerOneOffTask at the beginning of the callback.

**Comment by Flutter36** [comment]
Hi, 

I am trying to run periodic task on ios with below code and settings. Unfortunately, the task isnt getting triggered. Any help would be appreciated. 


Swift code:

import UIKit
import Flutter
import workmanager

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
     self.window.makeSecure() 
    GeneratedPluginRegistrant.register(with: self)
    UNUserNotificationCenter.current().delegate = self
    WorkmanagerPlugin.setPluginRegistrantCallback { registry in
        // Registry in this case is the FlutterEngine that is created in Workmanager's
        // performFetchWithCompletionHandler or BGAppRefreshTask.
        // This will make other plugins available during a background operation.
        GeneratedPluginRegistrant.register(with: registry)
    }

    WorkmanagerPlugin.registerPeriodicTask(withIdentifier: "com.background_task_manager.token_refresh_task", frequency: NSNumber(value: 20*60))
    //UIApplication.shared.setMinimumBackgroundFetchInterval(TimeInterval(20*60));
    
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  override func userNotificationCenter(
    _ center: UNUserNotificationCenter,
    willPresent notification: UNNotification,
    withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
      completionHandler(.alert) // shows banner even if app is in foreground
  }
}

extension UIWindow {
func makeSecure() {
    let isTestFlight = Bundle.main.appStoreReceiptURL?.lastPathComponent == "sandboxReceipt"
    let isSecureMode = Bundle.main.object(forInfoDictionaryKey: "EnableSecureMode") as! String == "YES"
    if (isTestFlight || !isSecureMode) {
      return
    }

    let field = UITextField()
    let view = UIView(frame: CGRect(x: 0, y: 0, width: field.frame.self.width, height: field.frame.self.height))
    field.isSecureTextEntry = true
    self.addSubview(field)
    self.layer.superlayer?.addSublayer(field.layer)
    field.layer.sublayers?.last!.addSublayer(self.layer)
    field.leftView = view
    field.leftViewMode = .always
  }
}


**version of the library used** 

  workmanager:
    git:
      url: https://github.com/absar/flutter_workmanager.git
      ref: 73cc539cd2f1b992b468e6c44f5d0a7919d7ffda
      
      
**Target platform an other details:**

platform :ios, '13.0'


**Code to trigger period task**
      
          Workmanager().registerPeriodicTask(
      BackgroundTaskKeys.refreshTokenTaskName, // Unique ID for your task
      BackgroundTaskKeys.refreshTokenTaskName,
      initialDelay: Duration(seconds: 10),
      frequency: Duration(seconds: 20*60)
    );
    
    
    Info LIst params
    
    		<key>UIBackgroundModes</key>
        <array>
		    <string>fetch</string>
		    <string>processing</string>
        </array>
        
        
        		<key>BGTaskSchedulerPermittedIdentifiers</key>
	    <array>
		    <string>com.kdi.background_task_manager.token_refresh_task</string>
        </array>

**Comment by ened** [comment]
Merging this, but will require a few iterations before packaging this into a release.

**Comment by yashmnp1910** [comment]
@ened Can you share the ETA for the new release?

**Comment by alfietapping** [comment]
Trying to run period task on ios results in this error

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(unhandledMethod("registerPeriodicTask") error, Unhandled method registerPeriodicTask, null, null)

Works fine on Android though, just an isolated iOS issue

**Comment by absar** [comment]
@alfietapping make sure to use the mentioned branch https://github.com/absar/flutter_workmanager/tree/ios-bg-tasks-enh-final instead of using master branch

**Comment by alfietapping** [comment]
@absar  thanks for this. The error has cleared, but unfortunately nothing actually happens now on iOS, workmanager never triggers any work. I've followed the specific ios setup from the docs, and i do get this line of code fire

BGAppRefreshTask submitted dailyReminder earliestBeginInSeconds:0.0

but it never runs the period task work declared in the main file, perhaps im missing something else?

**Comment by eserdeiro** [comment]
@alfietapping I have tried it, and it has worked for me.

Did you try opening Xcode, running your app, then in xcode going to 'debug -> simulate background fetch' ?

In my case, by doing that, my periodicTask has been executed after 8 minutes.

**Comment by sinhpn92** [comment]
I have the same issue on iOS. `registerProcessingTask` is not trigger on iOS.

**Comment by alfietapping** [comment]
> @alfietapping I have tried it, and it has worked for me.
> 
> Did you try opening Xcode, running your app, then in xcode going to 'debug -> simulate background fetch' ?
> 
> In my case, by doing that, my periodicTask has been executed after 8 minutes.
> 
> I am using the following in my pubspec
> 
> ```
> workmanager:
>    git:
>      url: https://github.com/fluttercommunity/flutter_workmanager.git
>      ref: b783000
> ```

Did you try actually running the process on a device and checking it ran work? I haven't tested simulating anything through xcode etc, if it doesn't work on a device then it doesn't function in the real world.

**Comment by andersonribeir** [comment]
> @alfietapping I have tried it, and it has worked for me.
> 
> Did you try opening Xcode, running your app, then in xcode going to 'debug -> simulate background fetch' ?
> 
> In my case, by doing that, my periodicTask has been executed after 8 minutes.
> 
> I am using the following in my pubspec
> 
> ```
> workmanager:
>    git:
>      url: https://github.com/fluttercommunity/flutter_workmanager.git
>      ref: b783000
> ```

i'm in this reference, but not triggered. OneOfTask works normally...

**Comment by andersonribeir** [comment]
> @alfietapping I have tested it on an Iphone 12 pro (physical device) with iOS 17.4.1 and it worked.
> 
> Remember to set minimum version iOS 13 in your flutter project.

I'm im iphone 11, ios 17.

OneOfTask works normally, but periodic doesn't, I'm not using initialValue, and I set the period to 15 minutes. What else should I try?

**Comment by FluffyDiscord** [comment]
I dont understand the steps here https://github.com/fluttercommunity/flutter_workmanager/blob/main/IOS_SETUP.md#testing-bgtaskscheduler

Where is the `submit()` that i need to find and add a breakpoint.

**Comment by xunreal75** [comment]
Hi. Please read references for this issue and add related Information in info.plist

BGTaskSchedulerErrorCodeNotPermitted = 3 - The task request could not be submitted because the appropriate background mode is not included in the UIBackgroundModes array, or its identifier was not present in the BGTaskSchedulerPermittedIdentifiers array in the app's Info.plist.

**Comment by Mistic92** [comment]
I'm using 
```
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      ref: b783000
```

While single everything works on Android on iOS I can't have working `Workmanager().registerPeriodicTask`. 

In my AppDelegate.swift I have
```
        // In AppDelegate.application method
        WorkmanagerPlugin.registerBGProcessingTask(withIdentifier: "xxxxxxxxx")

        // Register a periodic task in iOS 13+
        WorkmanagerPlugin.registerPeriodicTask(withIdentifier: "yyyyyyyyyyy", frequency: NSNumber(value: 15 * 60))        
```

In info.plist I have both identifiers
```
	<key>BGTaskSchedulerPermittedIdentifiers</key>
	<array>
		<string>xxxxxxxxx</string>
		<string>yyyyyyyyyyy</string>
	</array>
	<key>UIBackgroundModes</key>
	<array>
		<string>processing</string>
		<string>remote-notification</string>
		<string>fetch</string>
		<string>audio</string>
	</array>
```

and when I try to call registerPeriodicTask I see log "BGAppRefreshTask submitted yyyyyyyy earliestBeginInSeconds:0.0" but nothing happens even after 24h.

**Comment by rapkatt** [comment]
@Mistic92 
Did you find solution? I have same issue.

**Comment by delfme** [comment]
Same issue, periodic task is never fired on iOS physical device, even after 48h. Configration is correct and one off task works.

**Comment by absar** [comment]
I had updated the docs extensively as part of this PR, if you read carefully you will understand why iOS does not trigger periodic tasks or when it will:
https://github.com/absar/flutter_workmanager/blob/ios-bg-tasks-enh-final/IOS_SETUP.md#enable-bgtaskscheduler
https://github.com/absar/flutter_workmanager/tree/ios-bg-tasks-enh-final?tab=readme-ov-file#periodic-tasks

On iOS you can print scheduled tasks using [Workmanager.printScheduledTasks](https://github.com/absar/flutter_workmanager/tree/ios-bg-tasks-enh-final?tab=readme-ov-file#print-scheduled-tasks), if a task is scheduled and handed over to iOS that's it, as a developer your job is done, after that you cannot influence when it will run, its totally based on Apple and their usage pattern algorithm, if you just schedule a task a never use the app again in the coming days iOS might not even give your app background time, I personally experienced on latest iOS it takes at least two days to learn and probably from the third day it will start triggering if you have been using the app, also in the meantime if you uninstall the app and re-install all the usage pattern is reset which means once again it will not trigger for a few days. I also experienced if you use processing task it triggers it when your device is charging:

And lastly watch this video:
https://developer.apple.com/videos/play/wwdc2019/707

Regarding `requiresNetworkConnectivity` and `requiresExternalPower` these are swapped by mistake, there is already a PR but this repository is in abandoned state even though it is under Flutter Community which is sad since even Flutter docs refer to this plugin in official docs. Someone raised this [PR ](https://github.com/flutter/flutter/issues/163048) to adopt this plugin as first party package unfortunately it was rejected

**Comment by Vito0912** [comment]
> why iOS does not trigger periodic tasks or when it will:

It's not that it works only irregularly; it doesn't seem to work at all.

Note: Everything mentioned works on the emulator but not on a real device (as stated above by some).

> On iOS you can print scheduled tasks using [Workmanager.printScheduledTasks](https://github.com/absar/flutter_workmanager/tree/ios-bg-tasks-enh-final?tab=readme-ov-file#print-scheduled-tasks),

This printed that no tasks were scheduled on one test branch, even after a second start-up. On the current branch, it doesn't print anything (it is being called for sure, as the prints above and below are executed). I have not looked into it that much, but as many stated that it does not work while following the guide. See https://github.com/fluttercommunity/flutter_workmanager/pull/511#issuecomment-2228338532
He did not state if he tested to force the backrgound task, but I would assume he did.

Also, triggering the background fetch from Xcode settings or executing the command to force a background fetch does not work at all.

**Pull request merged**
