### PR TITLE
Restore compatibility with Flutter 1.20

### LINKED ISSUE #188: No support for flutter 1.20
I have tried debugging my application. But as soon as i include workmanager in my pubspec.yaml it can not compile.  This was working fine before the update.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > File 'com.android.builder.files.ZipCentralDirectory@229b9794' was deleted, but previous version not found in cache

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > File 'com.android.builder.files.ZipCentralDirectory@313e9a9e' was deleted, but previous version not found in cache

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

### LINKED ISSUE #217: NO Such Module workmanager on IOS side
- [x]  I have read the README
- [x]  I have done the setup for Android
- [x]  I have done the setup for iOS

0.2.0

please help guyss...

i have been follow all way on ios side and i have been read for all documentation but still got error 

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-ID)
    • Flutter version 1.20.4 at /Users/congfandi/development/flutter
    • Framework revision fba99f6cf9 (7 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/congfandi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API
      30) (emulator)
```

Screen Shot 2020-09-22 at 05 12 31

### PR DESCRIPTION
**Pull request by ened**
Closes #217 
Closes #188 

Testing instructions:

Add the following to your pubspec.yaml:

``` yaml
dependency_overrides:
  workmanager:
    git:
      url: https://github.com/ened/flutter_workmanager.git
      ref: 1c4e162ea4e71855856fb9e55a1545b3dae9a25d # flutter 1.20 compatibility
```

### CODE REVIEW

**Comment by ened** [comment]
@petermnt pls. take a look, thx.

**Comment by loolooii** [comment]
Any update on this PR?

**Comment by ened** [comment]
@petermnt hi, how are you doing? Are you available to check this PR soon?

**Review by prasadsunny1 — APPROVED** [review]

**Comment by ngothanhtai** [comment]
Checked on my side, it works.

**Comment by srombs** [comment]
Was hoping to get this merged in! Thanks!

**Comment by Tienisto** [comment]
Works in Flutter 1.22 👍

**Comment by adammach** [comment]
Could you please merge it?

**Comment by delizondo** [comment]
When will this be merged? I'm currently blocked in a project

**Comment by Tienisto** [comment]
This is my current state of pubspec.yaml using in a production app
```
workmanager:
    git:
      url: git@github.com:ened/flutter_workmanager.git
      ref: 1c4e162ea4e71855856fb9e55a1545b3dae9a25d
```

**Comment by delizondo** [comment]
@Tienisto getting the following error when adding that code:

`Git error. Command: `git clone --mirror git@github.com:ened/flutter_workmanager.git /Users/delizondo/flutter/.pub-cache/git/cache/flutter_workmanager-b145eb908d4135eaccf9e2d27cfe2100402b3876`

stdout: 

stderr: Cloning into bare repository '/Users/delizondo/flutter/.pub-cache/git/cache/flutter_workmanager-b145eb908d4135eaccf9e2d27cfe2100402b3876'...

Host key verification failed.

fatal: Could not read from remote repository.



Please make sure you have the correct access rights

and the repository exists.

exit code: 128
`

**Comment by ened** [comment]
@delizondo you need to use https. I have updated the instructions in the first post.

**Review by Tienisto — APPROVED** [review]

**Comment by delizondo** [comment]
Works perfect! Thanks @Tienisto

**Comment by Tienisto** [comment]
Thanks @ened

**Comment by amitkot** [comment]
This PR seems to fix the issue for me as well. 

I am currently considering several alternatives for implementing background tasks and trying this one as well.
I see this PR has been waiting for 3 months. Is this package actively maintained?

**Review by futurelucas4502 — APPROVED** [review]

**Review by luvishq — APPROVED** [review]

**Pull request merged**
